"""Initial database schema

Revision ID: 3e6a7d77aa4b
Revises: 
Create Date: 2026-07-03 04:50:30.411352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6a7d77aa4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tourist_id', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('snapshot_source', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_snapshot_captured_at'), 'location_snapshot', ['captured_at'], unique=False)
    op.create_index(op.f('ix_location_snapshot_tourist_id'), 'location_snapshot', ['tourist_id'], unique=False)
    op.create_table('risk_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('hazard_type', sa.Enum('EARTHQUAKE', 'FLOOD', 'LANDSLIDE', 'CYCLONE', 'DROUGHT', name='hazardtype'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['location_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_record_snapshot_id'), 'risk_record', ['snapshot_id'], unique=False)
    op.create_table('anomaly_alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_record_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['risk_record_id'], ['risk_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_alert_risk_record_id'), 'anomaly_alert', ['risk_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_alert_risk_record_id'), table_name='anomaly_alert')
    op.drop_table('anomaly_alert')
    op.drop_index(op.f('ix_risk_record_snapshot_id'), table_name='risk_record')
    op.drop_table('risk_record')
    op.drop_index(op.f('ix_location_snapshot_tourist_id'), table_name='location_snapshot')
    op.drop_index(op.f('ix_location_snapshot_captured_at'), table_name='location_snapshot')
    op.drop_table('location_snapshot')
    # ### end Alembic commands ###
