from datetime import datetime
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
)

from app.core.enums import (
    HazardType,
    RiskLevel,
)


# ==================================================
# Base Schema
# ==================================================

class RiskRecordBase(BaseModel):
    """
    Common fields shared by multiple
    RiskRecord schemas.
    """

    snapshot_id: UUID = Field(
        ...,
        description="LocationSnapshot associated with this prediction.",
    )

    hazard_type: HazardType = Field(
        ...,
        description="Type of detected hazard.",
        examples=["EARTHQUAKE"],
    )

    risk_level: RiskLevel = Field(
        ...,
        description="Predicted risk level.",
        examples=["HIGH"],
    )

    risk_score: float = Field(
        ...,
        ge=0,
        le=1,
        description="Normalized AI risk score.",
        examples=[0.91],
    )

    confidence: float = Field(
        ...,
        ge=0,
        le=1,
        description="Confidence of the AI prediction.",
        examples=[0.97],
    )

    model_version: str = Field(
        default="v1.0",
        max_length=20,
        description="AI model version.",
        examples=["v1.0"],
    )

    explanation: str = Field(
        ...,
        min_length=1,
        description="Human-readable explanation generated by the AI.",
        examples=[
            "Tourist is located inside a high seismic hazard zone."
        ],
    )


# ==================================================
# Create Schema
# ==================================================

class RiskRecordCreate(RiskRecordBase):
    """
    Request schema used when creating
    a new RiskRecord.
    """

    pass


# ==================================================
# Read Schema
# ==================================================

class RiskRecordRead(RiskRecordBase):
    """
    Response schema returned after
    reading a RiskRecord.
    """

    id: UUID

    predicted_at: datetime

    model_config = ConfigDict(
        from_attributes=True,
    )